Thank you page
DTS-STN/Alpha-Site pull request #113
Opened 2021-06-11 20:10 UTC by EphraimAssi

# Description

[success/thank you page after successful registration](https://trello.com/c/ESZzSCEo/241-241-success-thank-you-page-after-successful-registration)

Thank you after user has successfully submitted the form.
![image](https://user-images.githubusercontent.com/72703030/121743219-03756b80-cacf-11eb-9f02-c2d0b35a8a40.png)
![image](https://user-images.githubusercontent.com/72703030/121743449-6109b800-cacf-11eb-8f62-c10acc26739d.png)

## Acceptance Criteria

Fully translated and accessible

## Test Instructions

1. Fill the sign-up form correctly and submit, it should go to thank you page
2. Fill the sign-up form with mistakes and submit, it should not go to thank you page
3. Check the thank-you page on different screen sizes

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

2021-06-14 13:02 UTC, var-kyle reviewed
I just noticed a couple of things, but this is looking great! You're becoming a frontend pro!

2021-06-14 13:02 UTC, var-kyle commented on pages/thankyou.js
> +                href="mailto: Experience@servicecanada.gc.ca"
I'm not sure if the email will ever change, but parameterising it might be a good idea.

2021-06-14 14:47 UTC, EphraimAssi commented on pages/thankyou.js
> +              {t("confirmationP1")}&nbsp;
The &nbsp; was actually on purpose to fix a spacing issue I had.

2021-06-14 16:29 UTC, var-kyle requested changes

2021-06-14 16:29 UTC, var-kyle commented on pages/thankyou.js
> +                href={`mailto: ${t("confirmationEmail")}`}
I meant adding the email to props or as an env.

2021-06-14 17:46 UTC, EphraimAssi commented
I saw that the report a problem has the same email link in the env file, so I put that one.

2021-06-14 17:55 UTC, will0684 submitted a review, later dismissed
Looks and works great, nailed it! 👍

2021-06-14 20:00 UTC, var-kyle requested changes

2021-06-14 20:00 UTC, var-kyle commented on pages/thankyou.js
> +                href={`mailto: ${process.env.NOTIFY_REPORT_A_PROBLEM_EMAIL}`}
That's the right idea, but Nextjs needs you to add `NEXT_PUBLIC_` in front of an env to make it available to the client.

It currently will render as `mailto: undefined`
![image](https://user-images.githubusercontent.com/34345435/121951790-5fd3c780-cd29-11eb-900a-bd9f0dd98426.png)

This change would also have to be coordinated with Marcus so he can change the env in the pipeline as well.

2021-06-15 13:59 UTC, var-kyle approved these changes
Awesome, looks great!

Make sure Marcus updates the env in the pipeline before merging this PR though. It won't make the build fail, but we would have broken link for the email.

2021-06-15 17:05 UTC, merged