Accessibility audit - home page lacks meaningful heading structure
DTS-STN/Alpha-Site pull request #163
Opened 2021-07-06 20:04 UTC by var-kyle

# Description

From the accessibility audit:

Page lacks meaningful heading structure | Home | On this page, there are two heading level 1 "Service Canada Labs" and "Explore new services and help improve them". Both are acting as the main heading of the page.  Identify the main heading and update the second heading level to `<h2>`.  Also, the "Skip to main content" link should point to that heading which should be placed in the "Main" region of the page.
-- | -- | --

This PR moves the Banner component into the `<main>` region of the Layout component and updates to previous `<h1>` on the homepage to an `<h2>`. The skip to main content button links to the heading in the banner.

## Acceptance Criteria

Page structure updated as recommended from the accessibility audit

## Test Instructions

1. Navigate to the home page
2. Verify that there is only one `<h1>` and that the skip button links to it

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

2021-07-06 21:20 UTC, nibivi77 approved these changes
I feel like it would be better to skip the banner when "skipping content". Regardless, this should fix the issue in the audit.

Thank you!

2021-07-07 13:10 UTC, will0684 requested changes
I don't think we should be putting the banner in the main block. We have plans to bring in the DECD Design System later and it's Layout component is based on what we already had. It just doesn't make sense to me to skip to the title of the page in the banner when a screen reader user already knows the title of the page from the page title itself. I think we should just keep the banner heading an H1 and make the content heading an H2 and skip to the content heading.

2021-07-07 13:34 UTC, var-kyle commented
Good call @will0684, I misunderstood and thought the skip link had to point to the `<h1>` but that wasn't the case at all.

2021-07-07 15:24 UTC, will0684 approved these changes

2021-07-07 15:39 UTC, merged