Feedback popup
DTS-STN/Alpha-Site pull request #410
Opened 2021-10-27 13:12 UTC by shawn320

# Description

[#609 DEV Consider adding the feedback widget at the bottom of the page as well](https://jira-dev.bdm-dev.dts-stn.com/secure/RapidBoard.jspa?rapidView=96&projectKey=SCL&view=planning&selectedIssue=SCL-518&issueLimit=100)

Apply new design on the feedback widget, including add feedback on the bottom of the project page. 

**Feedback Popup**

<img width="982" alt="Screen Shot 2021-10-27 at 8 53 52 AM" src="https://user-images.githubusercontent.com/64853947/139070672-8860272d-f8dc-4e81-83ae-758eb7c979ec.png">

**Feedback at bottom of the page**

<img width="982" alt="Screen Shot 2021-10-27 at 8 54 04 AM" src="https://user-images.githubusercontent.com/64853947/139070708-aa1e40ce-6398-43f1-86cd-2559dbdb35aa.png">

**On mobile**

<img width="289" alt="Screen Shot 2021-10-27 at 8 56 15 AM" src="https://user-images.githubusercontent.com/64853947/139070838-4c225dff-9679-4620-a031-dc11648ff7f0.png">

## Test Instructions

1. Open project, go to `pages/projects/digital-centre.js`, change the `feedbackActive` state to false (line 36)
2. Start the development server, open browser and visit http://localhost:3000/projects/digital-centre
3. Test feedback popup on both top and bottom of the page

## Checklist

- [x] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated
- [x] Update CHANGELOG

2021-11-01 18:32 UTC, shawn320 commented on components/molecules/FeedbackWidget.js
> +    });
I think this is for the error message, and it definitely not needed anymore. Removed.

2021-11-01 18:37 UTC, shawn320 commented on pages/projects/digital-centre.js
> +  const [showFeedback, setShowFeedback] = useState(false);
The state is mapped to the `CallToAction` component, which will change the content of the banner at the bottom of the page. But I can remove the `setFeedbackActive`

2021-11-03 17:13 UTC, EphraimAssi reviewed
"Give feedback to help improve this website" seems to still be centered on lg screen sizes, I'm not sure if it was intentional.
![image](https://user-images.githubusercontent.com/72703030/140136210-56104746-429d-4cb7-b01c-8e6505708fd6.png)

2021-11-03 18:07 UTC, var-kyle requested changes
I like the improvements, and the focus trap works well!

One issue is that the form validation doesn't work anymore, you can submit an empty textbox and there won't be an error. The other thing is that there is some css work to be done. The close buttons don't look the best right now:
![image](https://user-images.githubusercontent.com/34345435/140167545-be7a67f7-260d-496d-aba3-a18b1deda785.png)

2021-11-03 18:14 UTC, shawn320 commented
> "Give feedback to help improve this website" seems to still be centered on lg screen sizes, I'm not sure if it was intentional. ![image](https://user-images.githubusercontent.com/72703030/140136210-56104746-429d-4cb7-b01c-8e6505708fd6.png)

Thank you for pointing it out, definitely not intentional, I'll see what I can do to fix it.

2021-11-03 18:15 UTC, shawn320 commented
> I like the improvements, and the focus trap works well!
> 
> One issue is that the form validation doesn't work anymore, you can submit an empty textbox and there won't be an error. The other thing is that there is some css work to be done. The close buttons don't look the best right now: ![image](https://user-images.githubusercontent.com/34345435/140167545-be7a67f7-260d-496d-aba3-a18b1deda785.png)

Thank you, I wasn't aware the empty submit issue, I'll look into it.

2021-11-04 17:22 UTC, var-kyle requested changes
It's looking a lot better and most issues are fixed, though still a couple of css problems.

In mobile view, the error after submitting doesn't display the text properly.
![image](https://user-images.githubusercontent.com/34345435/140388069-c557ec8f-57ab-413b-99ea-51154d2c3c83.png)

Also in mobile view, the button in the bottom CallToAction overflows off the screen.
![image](https://user-images.githubusercontent.com/34345435/140388176-1eab44ac-c4fc-4eb9-8338-e18128ed671f.png)

If I try to submit an empty field, I am getting the error now, but after closing the popup and opening it, the error is still there. Can you clear the error when closing the popup?

Overall it's looking great! Awesome work!

2021-11-05 18:29 UTC, var-kyle requested changes
The css fixes look great! I did end up seeing a couple of things that I should have noticed before though.

2021-11-05 18:29 UTC, var-kyle commented on components/molecules/FeedbackWidget.js
> +                            </a>
Could you please change this so that the email address isn't hard coded? You have it right in the `href` but then just wrote the email afterwards.

2021-11-05 18:29 UTC, var-kyle commented on components/molecules/FeedbackWidget.js
> +                    </a>
Same as above, can you remove the hard coded email addresses?

2021-11-05 18:45 UTC, var-kyle commented on components/molecules/FeedbackWidget.js
> +  }
I'm still not a huge fan of this, but we can send off for the a11y audit and see what they say, if anything.

2021-11-08 15:04 UTC, var-kyle approved these changes
Awesome work, thank you @shawn320!

2021-11-08 15:10 UTC, merged