Fix focus on feedback widget
DTS-STN/Alpha-Site pull request #466
Opened 2022-01-27 03:51 UTC by EphraimAssi

# Description

[Focus Indicator Disappears While Tabbing](https://jira-dev.bdm-dev.dts-stn.com/browse/SCL-606)

Fixed the focus indicator on the feedback widget on the close button and the email "experience@servicecanada.gc.ca"

## Test Instructions

1. Run the code locally
2. Check the feedback widget to see if the close button and the email "experience@servicecanada.gc.ca" focus on tab

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated
- [ ] Update CHANGELOG

## Product and Sprint Backlog

[Jira](https://jira-dev.bdm-dev.dts-stn.com/secure/RapidBoard.jspa?rapidView=96&projectKey=SCL)

2022-01-27 15:39 UTC, var-kyle requested changes
I like that you're making use of the ActionButton here, rather than `<button>` and `<a>` tags, it makes sense to use the components we have. I am a little concerned that the ActionButton is going to become to big, or hard to use since it has a lot of logic in it. But that's for some other time. The only thing I noticed was the use of `aria-label` that I think it incorrect.

2022-01-27 15:39 UTC, var-kyle commented on components/molecules/FeedbackWidget.js
> +                      ariaLabel="Service Canada email"
ActionButton renders as an `<a>` tag here, with text inside of it so there shouldn't be an `aria-label`.

2022-01-27 15:39 UTC, var-kyle commented on components/molecules/FeedbackWidget.js
> +                  imageSpanText={t("close")}
`aria-label` should only be used on elements that don't have text, or don't have a label associated with an image. In this case, there is a span inside the button with text, which accurately describes what the button does, so `aria-label` shouldn't be necessary here.

2022-01-31 19:01 UTC, krischarbonneau requested changes
Focus seems to work well now but NVDA announces "Undefined button" on every `ActionButton` so it the `imageSpanText` prop doesn't seem to be working

2022-01-31 23:07 UTC, EphraimAssi commented
I'm not sure why it's acting like that, but I put back the Aria-Labels

2022-02-01 19:13 UTC, krischarbonneau requested changes
The submit button still says `undefined button`, otherwise I think this is good

2022-02-02 20:11 UTC, krischarbonneau commented on components/molecules/FeedbackWidget.js
> +                    ariaLabel="Submit feedback button"
Should just be `Submit feedback`, otherwise screen readers will announce `Submit feedback button button`

2022-02-02 20:21 UTC, krischarbonneau commented on components/molecules/FeedbackWidget.js
> +                  custom="flex float-right pt-4 font-body text-gray-dark-100 flex mt-2.5 lg:mt-0 outline-none focus:outline-white-solid items-center"
The focus outline on the close button doesn't look that great. A work around here would be to get rid of the `pt-4` from the custom attribute and instead put this ActionButton inside a div with top padding. 

ie.
```JSX
              <div className="layout-container text-gray-dark-100 pb-4">
                <div className="pt-2">
                <ActionButton
                  id="feedbackClose"
                  ariaLabel="Close the expanded feedback section"
                  dataCy="closeButton"
                  dataTestId="closeButton"
                  custom="flex float-right font-body text-gray-dark-100 flex mt-2.5 lg:mt-0 outline-none focus:outline-white-solid items-center"
                  imageSource="/close-x.svg"
                  imageAlt="Close button"
                  imageSpanClass="text-xs leading-4 lg:text-sm underline ml-2 lg:leading-10"
                  imageSpanText={t("close")}
                  onClick={() => {
                    toggleForm();
                    setCount(2000);
                  }}
                />
                </div>
```


<img width="555" alt="Screenshot 2022-02-02 151703" src="https://user-images.githubusercontent.com/71025360/152230483-348842e6-d4bc-4ec7-98cb-4089cfe449f6.png">

2022-02-02 20:22 UTC, krischarbonneau reviewed
A couple more changes and this is good

2022-02-02 22:41 UTC, closed without merging