Text call to action component
DTS-STN/Alpha-Site pull request #58
Opened 2021-05-11 16:46 UTC by EphraimAssi

# Description

[Create text with call to action component](https://trello.com/c/sAiv36Ew/187-187-create-text-with-call-to-action-component)

Create a text with call to action component so that we can dynamically reference them according to the data in the CMS.
![image](https://user-images.githubusercontent.com/72703030/117853803-d37c4380-b256-11eb-8680-8ea839e9f7bb.png)

## Acceptance Criteria

Should be able to pass in CSS classes in order to change sizing i.e. full width half width etc

## Test Instructions

1. Test the page in different screen sizes
2. Compare the component with the Figma mock-up
3. Check the code to see if there's anything to improve
4. Check if add different widths size in the className Prop work.

## Checklist

- [x] Strings use placeholders for translation (No hard coded strings)
- [x] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

2021-05-11 17:11 UTC, Moro-Code requested changes
Good work overall !! There are some changes needed, let me know if you have any questions

2021-05-11 17:11 UTC, Moro-Code commented on components/molecules/TextButtonField.js
> +      ) : null}
do not pass null. Should either be undefined or an empty string

2021-05-11 17:11 UTC, Moro-Code commented on components/molecules/TextButtonField.js
> +      {props.text.map((paragraph, key) => {
Follow the example of setting markdown generated HTML from the NextJS tutorial. Array of text will not be passed in. Just HTML that needs to be set

2021-05-11 17:11 UTC, Moro-Code commented on components/molecules/TextButtonField.js
> +        <ActionButton
Let's make the secondary styling the default here

2021-05-11 17:11 UTC, Moro-Code commented on components/molecules/TextButtonField.js
> +    <div className={props.className + " mb-4"}>
Hmmm not sure this is working. 
![Screen Shot 2021-05-11 at 1 07 11 PM](https://user-images.githubusercontent.com/26819992/117856658-e17f9380-b259-11eb-9c7c-ae6317e327db.png)

2021-05-11 17:11 UTC, Moro-Code commented on components/molecules/TextButtonField.test.js
> +describe("TextButtonField", () => {
You need to flesh out your testing here. Is the button rendered in the correct styles ? Are you seeing the classes you pass in ? Is all the text rendered correctly on the page ?

2021-05-12 20:35 UTC, EphraimAssi commented
Changing the width seems to be working on my computer

2021-05-17 13:29 UTC, Moro-Code approved these changes
Great work @EphraimAssi !!

2021-05-17 13:34 UTC, merged