Helm chart and file Setup
DTS-STN/Alpha-Site pull request #6
Opened 2021-03-18 19:11 UTC by nghe0001

-Helmfiles and Helm chart imported to repo and setup

2021-03-18 20:17 UTC, will0684 requested changes

2021-03-18 20:17 UTC, will0684 commented on helm/charts/alphasite/Chart.yaml
> +description: Aplha Site
typo ;)

2021-03-18 22:57 UTC, Moro-Code requested changes
did you test this against the dev cluster ?

2021-03-19 11:55 UTC, nghe0001 commented on helm/charts/alphasite/Chart.yaml
> +description: Aplha Site
fixed =)

2021-03-19 13:02 UTC, nghe0001 commented
> did you test this against the dev cluster ?

did not have a img yesterday to test. Just got it tested with Adam this morning and is working fine now

2021-03-19 13:15 UTC, Moro-Code approved these changes
Good to merge

2021-03-19 14:01 UTC, will0684 approved these changes

2021-03-19 14:04 UTC, merged