Error404
DTS-STN/Alpha-Site pull request #81
Opened 2021-05-31 18:39 UTC by EphraimAssi

# Description

[Error 404 screens](https://trello.com/c/qhUPjDj9/121-121-error-404-screens)

I made a 404 error page following the Figma design.
![image](https://user-images.githubusercontent.com/72703030/120229945-46f0ef80-c21c-11eb-9267-506681e56abb.png)
![image](https://user-images.githubusercontent.com/72703030/120229991-625bfa80-c21c-11eb-821e-da35be4b9f88.png)

## Acceptance Criteria

It needs to fit the design for mobile and desktop on the Figma design.

## Test Instructions

1. Test a 404 error
2. 404 page should adapt to different screen sizes
3. There should be an English and French report a problem dropdown 

## Help Requested

For medium screen sizes, I didn't really know how to adapt the screen. So any recommendations is welcomed!

## Checklist
Only the report a problem dropdowns have no hard coded strings, I didn't think we needed it for the rest of the page since it's English and French but any feedback welcomed!

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

2021-05-31 19:19 UTC, Moro-Code requested changes
Hey, @EphraimAssi good stuff! A couple of things needed but in general really good! 

The footer element should always be at the bottom of the screen.
<img width="1792" alt="Screen Shot 2021-05-31 at 3 11 54 PM" src="https://user-images.githubusercontent.com/26819992/120233242-5b84b600-c223-11eb-95b9-843d305b1d82.png">

2021-05-31 19:19 UTC, Moro-Code commented on pages/404.js
> +              <p className="text-h1 font-bold font-display mb-4">
this should probably be an h1 element then

2021-05-31 19:19 UTC, Moro-Code commented on pages/404.js
> +              <p className="text-h1 font-bold font-display mb-4">
same here... should be h1

2021-05-31 19:19 UTC, Moro-Code commented on pages/404.js
> +            <img
hmmmmm we could we use the icon component for this ? perhaps in a button

2021-06-01 13:52 UTC, EphraimAssi commented
I adjusted the Report a problem in for large screen sizes because the French text wasn't fitting.

2021-06-01 14:18 UTC, Moro-Code reviewed
Hey looking good to merge. Just one more tiny thing.

2021-06-01 14:18 UTC, Moro-Code commented on components/atoms/ActionButton.js
> +      (props.iconEnd === undefined || props.iconEnd === false) ? (
you could just use `!props.iconEnd` here as undefined and false are falsey

2021-06-01 16:59 UTC, Moro-Code approved these changes
@EphraimAssi great great job !! Ship it 🚀

2021-06-01 17:01 UTC, merged