Button component
DTS-STN/Alpha-Site pull request #9
Opened 2021-03-19 20:57 UTC by EphraimAssi

I did a button component and unit testing following the servicePrototype as an example.
![image](https://user-images.githubusercontent.com/72703030/111841214-026bde00-88d4-11eb-83df-a1c7a5567e8b.png)

2021-03-22 15:53 UTC, Moro-Code requested changes
Great work overall ! Some changes! Lets try adding a cypress test to make sure the buttons are on the page. 

Can we also make sure to have the same fonts and colours as in the mockup ? 

![Screen Shot 2021-03-22 at 12 20 06 PM](https://user-images.githubusercontent.com/26819992/112022736-f2890f80-8b08-11eb-9df6-81523ffcc3ef.png)
![Screen Shot 2021-03-22 at 12 18 53 PM](https://user-images.githubusercontent.com/26819992/112022683-e8671100-8b08-11eb-8ffd-9be6d2385447.png)


![Screen Shot 2021-03-22 at 12 20 33 PM](https://user-images.githubusercontent.com/26819992/112022817-03398580-8b09-11eb-9a43-bcf8b0fa6dc1.png)
![Screen Shot 2021-03-22 at 12 20 21 PM](https://user-images.githubusercontent.com/26819992/112022774-fc127780-8b08-11eb-8b50-745a48631e62.png)

See tailwind documentation on how to add colours 
https://tailwindcss.com/docs/theme#colors

2021-03-22 15:53 UTC, Moro-Code commented on components/atoms/ActionButton.js
> +  invert: PropTypes.bool,
do we need this prop now ?

2021-03-22 15:53 UTC, Moro-Code commented on components/atoms/ActionButton.js
> +      data-cy={props.id}
Would like to make data-cy a separate prop here. Minor thing but its cleaner if they are seperate

2021-03-22 15:53 UTC, Moro-Code commented on components/atoms/ActionButton.stories.js
> +export const WithCounter = Template.bind({});
remove this story

2021-03-22 15:53 UTC, Moro-Code commented on components/atoms/ActionButton.stories.js
> +export const StartAgain = Template.bind({});
remove this story

2021-03-22 15:53 UTC, Moro-Code commented on components/atoms/ActionButton.js
> +  disabled: PropTypes.bool,
since we are passing in classNames now maybe we should have a prop to pass in styles for when the button is disabled

2021-03-22 17:12 UTC, pcraig3 reviewed
Hi Ephraim, good work! I made some suggestions, mostly about reducing the props to pass in. Hope it all makes sense.

2021-03-22 17:12 UTC, pcraig3 commented on components/atoms/ActionButton.js
> +          : "rounded-md"
We only have 1 style of button in the mockups, one with a small border radius. Can we take out the "rounded" option until it shows up?

2021-03-22 17:12 UTC, pcraig3 commented on components/atoms/ActionButton.js
> +  rounded: PropTypes.bool,
I think let's get rid of the "rounded" options. See above comment.

2021-03-22 17:12 UTC, pcraig3 commented on components/atoms/ActionButton.stories.js
> +Primary.args = {
Yeah, I also don't see the blue background in the storybook links. Do you know why that is?

2021-03-22 17:12 UTC, pcraig3 commented on pages/index.js
> +            }
We pretty have 2 button styles so far, the blue and the alternate white with blue text. Can we make this the default for our use-case?

2021-03-24 13:31 UTC, pcraig3 requested changes
Two more changes requested, based on looking at the Canada.ca buttons.

![buttons](https://user-images.githubusercontent.com/2454380/112318541-87177d00-8c83-11eb-920d-c3fddf97a3ca.gif)


1. The [canada.ca buttons](https://design.canada.ca/common-design-patterns/buttons.html) have an "`:active`" state that's different than the focus + hover state. 'active' means that you are actually pressing the button. When you click on the canada.ca buttons, their colour changes (in addition to the focus ring).
2. The focus ring is more pronounced on the Canada.ca buttons because they are using outline offset. Our focus ring (especially for the blue button) is way less noticeable. I would say let's make the focus ring a bit more prominent for our buttons: either use the outline offset + border that canada.ca uses, or let's just make the border thicker.

Here's ours for comparison. Note how clicking on the buttons doesn't change the bg colour.

![buttons2](https://user-images.githubusercontent.com/2454380/112318647-a7dfd280-8c83-11eb-96e3-f1488e10f457.gif)

2021-03-24 16:01 UTC, pcraig3 approved these changes
Looks good Ephraim, thanks!

2021-03-24 16:19 UTC, merged