Skip button
DTS-STN/Alpha-Site pull request #93
Opened 2021-06-04 14:36 UTC by EphraimAssi

# Description

[Create a "Skip to Content" link in the layout for a11y](https://trello.com/c/1hxhUiQZ/231-231-create-a-skip-to-content-link-in-the-layout-for-a11y)

I made Skip to Content button accessible for keyboard users to skip straight to the main content without going through multiple things with tab.
![image](https://user-images.githubusercontent.com/72703030/120817919-1eb90780-c520-11eb-85d8-158f3b49d0b4.png)

## Acceptance Criteria

Skip to main content button should be the first thing reachable with tab and also should skip to the main title.

## Test Instructions

1. Test the button to see if it skips to the main title on each page (Home, Experiments, About)
2. It should always be invisible unless it's focused
3. It should always be centered horizontally no matter the screen size

## Help Requested

- I put the place under the alpha banner since like Canada.ca doesn't have an alpha banner but if anyone has suggestions for placement, I'm open to it!

## Checklist

- [ ] Strings use placeholders for translation (No hard coded strings)
- [ ] Unit tests have been added/updated

## Product and Sprint Backlog

[Trello](https://trello.com/b/ZqWtJSyh/alpha-site-board)

2021-06-04 16:36 UTC, will0684 requested changes
Looking really good! One issue I'm seeing. When you click on the "Skip to content" button and then scroll back up on the same page and try to toggle the language, it won't let you change the language but instead keeps activating the skip to content.

2021-06-04 17:50 UTC, pcraig3 commented
2 things, Ephraim.

1. The accessibility checklist:

On [the accessibility checklist](https://bati-itao.github.io/resources/a11ycheck-en.html), there's a list that says Focus is always visible (using keyboard). 
- When we use the skip link [on Canada.ca](https://www.canada.ca/en.html), it highlights the main header with.a focus ring
- On our page, we don't have a H1 focus style at all, so we should add one when it's focused.

2. Jordan is right, the french link stops working.

The french link seems like it literally updates the "href" on the page when you add a #hash to the end of a URL. We don't want the "French" link to update after clicking the skip link, so maybe we should try using an `<a>` tag here instead of the `<Link>` component for the language link: https://github.com/DTS-STN/Alpha-Site/blob/main/components/organisms/Layout.js#L45

2021-06-07 13:14 UTC, will0684 requested changes
Nice work! One tiny thing and then it will be good to merge

2021-06-07 13:14 UTC, will0684 commented on components/organisms/Layout.js
> +          dataCyButton={"skip-Content"}
Getting a warning for this attribute 
![image](https://user-images.githubusercontent.com/31868510/121022790-abf29b00-c770-11eb-87eb-71eadf13c526.png)

2021-06-07 14:14 UTC, pcraig3 approved these changes
Tried it out again and it works great! Good work, @EphraimAssi! (Let's wait for Jordan to review too though)

2021-06-07 14:17 UTC, will0684 approved these changes

2021-06-07 14:18 UTC, merged